using Franz.Common.Mediator.SourceGenerator.Discovery;
using System.Collections.Generic;
using System.Text;

namespace Franz.Common.Mediator.SourceGenerator.Generation;

internal static class RegistrationSourceEmitter
{
  public static string Generate(IEnumerable<HandlerInfo> handlers)
  {
    var builder = new StringBuilder();

    builder.AppendLine(@"// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Franz.Common.Mediator.Registration;

namespace Franz.Common.Mediator.Registration;

/// <summary>
/// Compile-time generated handler registration provider for Franz Mediator.
/// </summary>
public sealed class FranzMediatorGeneratedRegistration : IHandlerRegistrationProvider
{
    public void Register(IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);
");

    var registeredKeys = new HashSet<string>();

    foreach (var handler in handlers)
    {
      var key = $"{handler.ServiceType}|{handler.ImplementationType}";
      if (!registeredKeys.Add(key))
        continue;

      builder.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Scoped(typeof({handler.ServiceType}), typeof({handler.ImplementationType})));");
    }

    builder.AppendLine(@"    }
}");

    return builder.ToString();
  }
}