using System;
using System.Collections.Generic;
using System.Text;

namespace Franz.Common.Business.Domain.IdGenerators;

public sealed class DbIdGenerator<TId> : IIdGenerator<TId>
{
  public TId Create()
      => throw new InvalidOperationException("Generated by database");
}