//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franz.Common.Messaging.Hosting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Franz.Common.Messaging.Hosting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.Body is not deserializable.
        /// </summary>
        public static string EventMessagingStrategyExecuterEventParameterDeserializationException {
            get {
                return ResourceManager.GetString("EventMessagingStrategyExecuterEventParameterDeserializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.Header does not contain a valid type for event parameter.
        /// </summary>
        public static string EventMessagingStrategyExecuterEventParameterException {
            get {
                return ResourceManager.GetString("EventMessagingStrategyExecuterEventParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.Body does not implement {0}.
        /// </summary>
        public static string EventMessagingStrategyExecuterEventParameterNotImplementedException {
            get {
                return ResourceManager.GetString("EventMessagingStrategyExecuterEventParameterNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.Body must not be null.
        /// </summary>
        public static string EventMessagingStrategyExecuterEventParameterNullException {
            get {
                return ResourceManager.GetString("EventMessagingStrategyExecuterEventParameterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructor found with two parameters &apos;{0}&apos;, &apos;{1}&apos;.
        /// </summary>
        public static string HostBuilderExtensionsNoConstructorFoundException {
            get {
                return ResourceManager.GetString("HostBuilderExtensionsNoConstructorFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method &apos;ConfigureServices&apos; found.
        /// </summary>
        public static string HostBuilderExtensionsNoMethodFoundException {
            get {
                return ResourceManager.GetString("HostBuilderExtensionsNoMethodFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No strategy found to process the message.
        /// </summary>
        public static string StrategyExecuterNotFoundException {
            get {
                return ResourceManager.GetString("StrategyExecuterNotFoundException", resourceCulture);
            }
        }
    }
}
