using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Franz.Common.Mapping.Generators;

[Generator]
public class MapperGenerator : IIncrementalGenerator
{
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Step 1: Filter for partial classes.
    var provider = context.SyntaxProvider.CreateSyntaxProvider(
        predicate: static (s, _) => s is ClassDeclarationSyntax { Modifiers: var m } && m.Any(mod => mod.ValueText == "partial"),
        transform: static (ctx, _) => GetMapperTarget(ctx))
        .Where(static m => m is not null);

    // Step 2: Generate source.
    context.RegisterSourceOutput(provider, static (spc, target) =>
    {
      if (target is not MapperTargetInfo info) return;
      var sourceText = GenerateMapperClass(info);
      spc.AddSource($"{info.ClassName}.g.cs", SourceText.From(sourceText, Encoding.UTF8));
    });
  }

  private static MapperTargetInfo? GetMapperTarget(GeneratorSyntaxContext context)
  {
    var classDeclaration = (ClassDeclarationSyntax)context.Node;

    // FIX: Cast to INamedTypeSymbol to access .Interfaces
    if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
      return null;

    // Use AllInterfaces to catch implementations in base classes if necessary
    var mapperInterface = symbol.AllInterfaces.FirstOrDefault(i =>
        i.Name is "IMapper" or "IAsyncMapper");

    if (mapperInterface is null || mapperInterface.TypeArguments.Length < 2)
      return null;

    var sourceType = mapperInterface.TypeArguments[0];
    var destType = mapperInterface.TypeArguments[1];

    return new MapperTargetInfo(
        symbol.ContainingNamespace.ToDisplayString(),
        symbol.Name,
        sourceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
        destType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
        mapperInterface.Name == "IAsyncMapper",
        GetMatchingProperties(sourceType, destType)
    );
  }

  private static ImmutableArray<string> GetMatchingProperties(ITypeSymbol source, ITypeSymbol destination)
  {
    // Dictionary lookup for O(N) property matching
    var srcProps = source.GetMembers().OfType<IPropertySymbol>()
        .Where(p => p.CanBeReferencedByName && !p.IsStatic)
        .ToDictionary(p => p.Name, StringComparer.Ordinal);

    var destProps = destination.GetMembers().OfType<IPropertySymbol>()
        .Where(p => p.CanBeReferencedByName && !p.IsStatic && p.SetMethod is not null);

    var matches = ImmutableArray.CreateBuilder<string>();
    foreach (var dest in destProps)
    {
      if (srcProps.TryGetValue(dest.Name, out var src) &&
          SymbolEqualityComparer.Default.Equals(src.Type, dest.Type))
      {
        matches.Add(dest.Name);
      }
    }
    return matches.ToImmutable();
  }

  private static string GenerateMapperClass(MapperTargetInfo target)
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine($"namespace {target.Namespace};");
    sb.AppendLine();
    sb.AppendLine($"public partial class {target.ClassName}");
    sb.AppendLine("{");

    if (target.IsAsync)
    {
      sb.AppendLine($"    public partial async System.Threading.Tasks.ValueTask<{target.DestinationType}> MapAsync({target.SourceType} source, System.Threading.CancellationToken cancellationToken)");
      sb.AppendLine("    {");
      sb.AppendLine("        if (source is null) return default!;");
      AppendMappingPayload(sb, target);
      sb.AppendLine("        return result;");
      sb.AppendLine("    }");
    }
    else
    {
      sb.AppendLine($"    public partial {target.DestinationType} Map({target.SourceType} source)");
      sb.AppendLine("    {");
      sb.AppendLine("        if (source is null) return default!;");
      AppendMappingPayload(sb, target);
      sb.AppendLine("        return result;");
      sb.AppendLine("    }");
    }

    sb.AppendLine("}");
    return sb.ToString();
  }

  private static void AppendMappingPayload(StringBuilder sb, MapperTargetInfo target)
  {
    sb.AppendLine($"        var result = new {target.DestinationType}");
    sb.AppendLine("        {");
    foreach (var prop in target.MatchedProperties)
    {
      sb.AppendLine($"            {prop} = source.{prop},");
    }
    sb.AppendLine("        };");
  }

  // Record struct provides built-in Equality for Incremental Generator caching
  private record struct MapperTargetInfo(
      string Namespace,
      string ClassName,
      string SourceType,
      string DestinationType,
      bool IsAsync,
      ImmutableArray<string> MatchedProperties);
}